Upgrade terraform-provider-aws to v3.41.0
pulumi/pulumi-azure pull request #1203
Opened 2023-02-02 19:52 UTC by thomas11

- Upgrade to terraform-provider-aws v3.41.0
- Regenerate SDKs after upgrade to terraform-provider-aws v3.41.0

2023-02-02 20:14 UTC, kpitzen approved these changes

2023-02-03 19:28 UTC, danielrbradley requested changes
Ignore earlier comment ... thought this was a bridge upgrade. Need to work out why that test is failing if there's no schema change affecting it though 🤔

2023-02-03 20:06 UTC, danielrbradley reviewed
Looks like there's already a coulpe of people looking at this so I'll just let you carry on!

Error is a bit unusual and I doubt a retry will help. I wonder if there's something changed in the upstream provider here? Possibly another instance of the MaxItemsOne issue: https://github.com/pulumi/platform-providers-team/blob/main/playbooks/maxitemsone.md

```
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Missing required argument: The argument "frontend_endpoint" is required, but no definition was found.. Examine values at 'Frontdoor.FrontendEndpoints'.
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Missing required argument: The argument "routing_rule" is required, but no definition was found.. Examine values at 'Frontdoor.RoutingRules'.
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Missing required argument: The argument "backend_pool" is required, but no definition was found.. Examine values at 'Frontdoor.BackendPools'.
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Value for unconfigurable attribute: Can't configure a value for "backend_pools": its value will be decided automatically based on the result of applying this configuration.. Examine values at 'Frontdoor.BackendPools'.
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Value for unconfigurable attribute: Can't configure a value for "routing_rules": its value will be decided automatically based on the result of applying this configuration.. Examine values at 'Frontdoor.RoutingRules'.
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Value for unconfigurable attribute: Can't configure a value for "backend_pool_health_probes": its value will be decided automatically based on the result of applying this configuration.. Examine values at 'Frontdoor.BackendPoolHealthProbes'.
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Value for unconfigurable attribute: Can't configure a value for "frontend_endpoints": its value will be decided automatically based on the result of applying this configuration.. Examine values at 'Frontdoor.FrontendEndpoints'.
  error: azure:frontdoor/frontdoor:Frontdoor resource 'example' has a problem: Missing required argument: The argument "backend_pool_health_probe" is required, but no definition was found.. Examine values at 'Frontdoor.BackendPoolHealthProbes'.
```

2023-02-03 20:08 UTC, thomas11 commented
> Ignore earlier comment ... thought this was a bridge upgrade. Need to work out why that test is failing if there's no schema change affecting it though 🤔

@danielrbradley @rquitales is working on it

2023-02-07 16:21 UTC, danielrbradley approved these changes

2023-02-07 19:28 UTC, merged