Increase default runner to pulumi-ubuntu-8core
pulumi/pulumi-azure pull request #1385
Opened 2023-10-12 18:49 UTC by rquitales

To help unblock all CI jobs.

2023-10-12 18:51 UTC, iwahbe approved these changes

2023-10-12 18:51 UTC, iwahbe commented on .ci-mgmt.yaml
>    publish: pulumi-ubuntu-8core
Nit: We can comment these out if we want, since they are overriding the default *and* the same as the default.

2023-10-16 16:27 UTC, guineveresaenger requested changes
I think most of these aren't really necessary.

Most of these were addressed via logic in the ci-mgmt templates (the templates decide which runner to assign based on the config field set), and passed to pulumi-azure's Workflows via [PRs like this one](https://github.com/pulumi/pulumi-azure/commit/f2928e097779e9a0f039665b26955faf60520032).

See also changes applied [here](https://github.com/pulumi/pulumi-azure/blob/master/.github/workflows/release.yml#L222).

I think we can close this out.

2023-10-23 16:44 UTC, iwahbe commented
@rquitales Can we close this?

2023-10-24 16:37 UTC, rquitales commented
Stale PR.

2023-10-24 16:37 UTC, closed without merging